#!/bin/bash

echo " "
warna='\e[40;38;5;82m'
echo -e "${warna} +--------------------------+ \e[0m"
echo -e "${warna} ¦  Mulai auto setup bind9  ¦ \e[0m"
echo -e "${warna} +--------------------------+ \e[0m"
echo " "
echo -e "${warna} +--------------------------+ \e[0m"
echo -e "${warna} ¦  Update db paket system  ¦ \e[0m"
echo -e "${warna} +--------------------------+ \e[0m"
apt-get -y -qq update
echo " "
echo -e "${warna} +--------------------------+ \e[0m"
echo -e "${warna} ¦   Upgrade paket system   ¦ \e[0m"
echo -e "${warna} +--------------------------+ \e[0m"
apt-get -y -qq upgrade
echo " "
echo -e "${warna} +--------------------------+ \e[0m"
echo -e "${warna} ¦  Install aplikasi bind9  ¦ \e[0m"
echo -e "${warna} +--------------------------+ \e[0m"
apt-get -y -qq install bind9 bind9utils dos2unix
echo " "
echo -e "${warna} +--------------------------+ \e[0m"
echo -e "${warna} ¦  Hentikan service bind9  ¦ \e[0m"
echo -e "${warna} ¦  Dan persiapkan config   ¦ \e[0m"
echo -e "${warna} +--------------------------+ \e[0m"
service bind9 stop
curl -s https://raw.githubusercontent.com/ucokkarnadi/OPIZ/master/conf > /etc/bind/named.conf.options
curl -s https://raw.githubusercontent.com/ucokkarnadi/OPIZ/master/block.zone >  /etc/bind/block.zone
curl -s https://raw.githubusercontent.com/ucokkarnadi/OPIZ/master/block.custom >  /etc/bind/block.custom
curl -s https://raw.githubusercontent.com/ucokkarnadi/OPIZ/master/pass.zone >  /etc/bind/pass.zone
curl -s https://raw.githubusercontent.com/ucokkarnadi/OPIZ/master/pass.data >  /etc/bind/pass.data

curl -s https://raw.githubusercontent.com/ucokkarnadi/OPIZ/master/update > /usr/local/bin/update
/bin/bash /usr/local/bin/update

chmod 666 /etc/bind/pass.*
chown bind:bind /etc/bind/pass.*
chmod 666 /etc/bind/block.*
chown bind:bind /etc/bind/block.*

echo " "
echo -e "${warna} +--------------------------+ \e[0m"
echo -e "${warna} ¦ Tambah crontab auto sync ¦ \e[0m"
echo -e "${warna} +--------------------------+ \e[0m"
(crontab -l; echo "* 3 * * * /bin/bash /usr/local/bin/update;") | sort -u | crontab - ; crontab -l
echo " "
echo -e "${warna} +--------------------------+ \e[0m"
echo -e "${warna} ¦   Start service bind9    ¦ \e[0m"
echo -e "${warna} +--------------------------+ \e[0m"
service bind9 start
service bind9 status | head -25
echo " "
IP=`hostname -I`
echo -e "${warna} +--------------------------+ \e[0m"
echo -e "${warna} ¦   Setup seleai arahkan   ¦ \e[0m"
echo -e "${warna} ¦   DNS konsumen ke IP     ¦ \e[0m"
echo -e "${warna}        $IP         \e[0m"
echo -e "${warna} ¦                          ¦ \e[0m"
echo -e "${warna} ¦   Untuk statistik DNS    ¦ \e[0m"
echo -e "${warna}    http://$IP:8888
echo -e "${warna} +--------------------------+ \e[0m"
