#!/bin/bash

exec 1> >(logger -s -t $(basename $0)) 2>&1

cd /tmp/
curl -s https://raw.githubusercontent.com/ucokkarnadi/OPIZ/master/dom.list >  /tmp/url.list
rm -rf dom.new;
rm -rf dom.old;
touch dom.new;
touch dom.old;
touch /etc/bind/block.data;
cat /etc/bind/block.data |  grep -v -e '^$' -e '^\s*$' | awk '{print $1}' | sort -u > dom.list
cat dom.list > dom.old

for i in $(cat url.list);
do
curl -s $i | awk '{$1=$1}1'| grep -v -e '^#' -e '^$' -e '^\s*$' -e 'localhost$' -e 'broadcasthost' | \
sed -e 's/0.0.0.0//g;s/127.0.0.1//g' | awk '{$1=$1}1' | sed 's/ #.*$//;s/#.*$//' | \
grep -v -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(\/|$)' | grep -v -e '^\.' -e '^-' -e ':' -e ' list '>> dom.list
done

dos2unix -q dom.list

for i in $(cat dom.list | sort -u)
do
echo $i >> dom.temp
done

cat dom.temp | sort -u > dom.new


diff -c dom.old dom.new | grep "+" | awk '{$1=""}1' | awk '{$1=$1}1'  |  grep -v -e '^$' -e '^\s*$' | sort -u | \
awk '{print $1 "\tIN\tCNAME\t*."}' >> /etc/bind/block.data


for i in $(named-checkzone block /etc/bind/block.zone | grep ignoring | awk -F'(' '{print $2}' | sed 's/)//');
do
sed -i "/$i/d" /etc/bind/block.data;
done

cat /etc/bind/block.data |  grep -v -e '^$' -e '^\s*$' | awk '{print $1}' | sort -u > dom.new


if [ $(diff -c dom.old dom.new | grep "+" | awk '{$1=""}1' | awk '{$1=$1}1'  |  grep -v -e '^$' -e '^\s*$' | wc -l) -gt 10 ]
then

SOAF="/etc/bind/block.zone"
DATE=$(date +%Y%m%d)
curr=$(sed -n '/^@/,/^[^;]*)/H;${;x;s/.*@[^(]*([^0-9]*//;s/[^0-9].*//;p;}' $SOAF)
prefix=${curr::-2}
if [ "$DATE" -eq "$prefix" ]; then
    num=${curr: -2}
    num=$((10#$num + 1))
    serial="${DATE}$(printf '%02d' $num )"
else
    serial="${DATE}00"
fi
sed -i "s/[0-9]\{10\}/${serial}/g" $SOAF

/usr/sbin/rndc reload

fi

